version: "3.7"
services:
  web:
    #image: php:7.4.1-zts-alpine
    image: franciscoj/php-hello-world:latest
    #build: .
    ports:
      - "80:8080"
        #volumes:
        #- .src/public_html:/var/www/html
        #- .apache2:/etc/apache2
    environment:
      - VIRTUAL_HOST=blogsite.com
        #    depends_on:
        #- db
        #command: "php -S 0.0.0.0:8080 -t /var/www/html" 
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
       
        #  db:
        #    build: ./docker/mysql 
